# Generated by Django 3.2.15 on 2022-08-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=30, unique=True)),
                ('no_of_places', models.IntegerField()),
                ('open', models.IntegerField(choices=[(0, 'Open'), (1, 'Booked')], default=0)),
                ('table_size', models.IntegerField(choices=[(2, '2-Places'), (4, '4-Places'), (6, '6-Places'), (8, '8-Places')])),
            ],
            options={
                'ordering': ['table_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('town_city', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(unique=True)),
                ('booking_date', models.DateTimeField()),
                ('booking_time', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('no_of_guests', models.IntegerField()),
                ('paid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tables')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
    ]
