# Generated by Django 3.2.15 on 2022-08-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
