# Generated by Django 3.2.15 on 2022-08-28 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_no_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_id',
            field=models.CharField(default='A1', max_length=30),
            preserve_default=False,
        ),
    ]
