# Generated by Django 3.2.15 on 2022-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_id',
            field=models.CharField(default='000', max_length=30),
        ),
    ]
