# Generated by Django 3.2.15 on 2022-12-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_id',
            field=models.CharField(max_length=30),
        ),
    ]
