# Generated by Django 3.2.15 on 2022-08-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='login_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
