# Generated by Django 3.2.15 on 2022-08-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='login_id',
            new_name='login_name',
        ),
    ]
