# Generated by Django 3.2.15 on 2022-08-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_login_name_booking_login_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_join',
            new_name='BookingJoin',
        ),
    ]
