# Generated by Django 3.2.15 on 2022-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20220825_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirm',
            field=models.IntegerField(default=0),
        ),
    ]
