# Generated by Django 3.2.15 on 2022-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirm',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
